# Generated by Django 4.2.4 on 2024-01-15 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
