# Generated by Django 5.0.1 on 2024-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_customuser_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
