# Generated by Django 5.0.1 on 2024-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubMembers', '0002_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
