# Generated by Django 5.0.1 on 2024-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubMembers', '0003_alter_club_contact_email_alter_club_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], max_length=10),
        ),
    ]
